version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv  # Exclude .venv from volume mount
    # depends_on:
    #   - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

  # Optional: Database (uncomment if needed)
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: fastapi_starter
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   redis_data:
#   postgres_data:
