# https://taskfile.dev

version: "3"

vars:
  CONTAINER_NAME: ghcr.io/openimagingdata/findingmodelforge:latest

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build_image:
    desc: "Build the findingmodelforge Docker image"
    cmds:
      - echo "Building API image..."
      - docker build --platform linux/amd64 -t {{.CONTAINER_NAME}} .
    silent: true
  
  check:
    desc: "Linting/formatting/type checking"
    cmds:
      - echo "Checking library..."
      - uv run ruff format
      - uv run ruff check --fix
      - uv run mypy findingmodelforge
    silent: true

  run:
    desc: "Run the findingmodelforge app natively"
    cmds:
      - uv run uvicorn findingmodelforge.main:app --log-level info --reload  --host localhost --port 8000
    silent: true
  
  run_container:
    desc: "Run the findingmodelforge app in a container"
    cmds:
      - echo "Running API container..."
      - docker run --name findingmodelforge --platform linux/amd64 -d --env-file .env -p 8000:8000 --rm {{.CONTAINER_NAME}} /app/run_app.sh
    silent: true