services:
  proxy:
    image: traefik:v3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tarik@alkasab.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"     
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
  fmfweb:
    image: ghcr.io/openimagingdata/findingmodelforge-api:latest
    ports:
      - 8000:8000
    environment:
      INFISICAL_PROJECT_ID: "f665fe3d-3768-47ff-af97-77c9cb2a186e"
      INFISICAL_CLIENT_ID: "0bb3100b-ea32-4281-b3d0-c79015155942"
      AUTH_REDIRECT_URI: "https://fmf-dev.openimagingdata.org/callback"
    env_file:
      - path: .env
        required: true
    command: ./run_app_prod.sh
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fmfweb.rule=Host(`fmf-dev.openimagingdata.org`)"
      - "traefik.http.routers.fmfweb.entrypoints=websecure"
      - "traefik.http.routers.fmfweb.tls.certresolver=myresolver"
    restart: always
volumes:
  letsencrypt: