[project]
name = "findingmodelforge"
version = "0.1.0"
description = "Functionality for creating imaging finding models/semantic labels"
authors = [
    { name = "Tarik Alkasab", email = "info@openimagingdata.org" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
