[project]
name = "fmf-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "findingmodelforge",
    "nicegui>=2.5.0",
    "pydantic-settings>=2.6.1",
]

[dependency-groups]
dev = [
    "commitizen>=3.31.0",
    "mypy>=1.13.0",
    "ruff>=0.7.2",
]

[tool.uv.sources]
findingmodelforge = { path = "../findingmodelforge", editable = true }
