[project]
name = "findingmodelforge"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tarik Alkasab", email = "tarik@alkasab.org" }
]
requires-python = ">=3.11"
dependencies = [
    "beanie>=1.27.0",
    "motor>=3.6.0",
    "pydantic>=2.9.2",
    "pymongo>=4.9.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "ruff>=0.7.2",
    "jupyter>=1.1.1",
]
