[project]
name = "findingmodelforge"
version = "0.1.0"
description = "Tools for building data models of imaging findings"
authors = [
    { name = "Tarik Alkasab", email = "tarik@alkasab.org" },
    { name = "Vijay Dawal", email = "vijaydawal@microsoft.com" },
    { name = "Yilun Zhang", email = "zhangyilun1337@gmail.com" },
    { name = "Catie Ladd", email = "catieladd@microsoft.com" },
]
requires-python = ">=3.11"
dependencies = [
    "beanie>=1.27.0",
    "dynaconf>=3.2.6",
    "instructor>=1.6.4",
    "jinja2>=3.1.4",
    "motor>=3.6.0",
    "openai>=1.54.4",
    "pydantic-settings>=2.6.1",
    "pydantic>=2.9.2",
    "pymongo>=4.9.2",
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/openimagingdata/FindingModelForge"
Issues = "https://github.com/openimagingdata/FindingModelForge/issues"

[project.scripts]
fmf_cli = "fmf_cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "ruff>=0.7.2",
    "jupyter>=1.1.1",
    "commitizen>=3.30.1",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
    "needs_db: Marks tests as needing a database connection",
    "asyncio: Marks tests as needing asyncio",
]

[tool.commitizen]
version_provider = "pep621"
tag_format = "v$version"
version_files = ["pyproject.toml:version", "src/findingmodelforge/__init__.py"]
update_changelog_on_bump = true
