[project]
name = "findingmodelforge"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tarik Alkasab", email = "tarik@alkasab.org" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.7.2",
]
