[development]
DEBUG = true
MONGO_DSN = "mongodb://localhost:27017"
DATABASE_NAME = "findingmodelforge"

[testing]
DEBUG = true
MONGO_DSN = "mongodb://localhost:27017"
DATABASE_NAME = "fmf_test"

[production]
DEBUG = false
DATABASE_NAME = "findingmodelforge"