[default]
MONGO_DSN = "mongodb://localhost:27017"
DATABASE_NAME = "findingmodelforge"
PERPLEXITY_BASE_URL = "https://api.perplexity.ai"

[development]
DEBUG = true

[testing]
DEBUG = true
DATABASE_NAME = "fmf_test"

[production]
DEBUG = false
